### ISSUE TITLE
feat: create home page

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/Website#1]
### Make home page for code sauce

![image](https://user-images.githubusercontent.com/53532851/123139462-dc764c80-d473-11eb-835d-5ff639212d72.png)

### Figma Link
https://www.figma.com/file/aIGds1IG7Kz03UBOakEKjf/Code-Sauce-Website-Design?node-id=0%3A1

**Comment by ayushseth07** [comment]
please assign this issue to me

**Comment by SHITIZ-AGGARWAL** [comment]
Sure go ahead
