### ISSUE TITLE
feat: create about page

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/Website#2]
### Make about us page for code sauce website

![image](https://user-images.githubusercontent.com/53532851/123139755-2e1ed700-d474-11eb-8ff8-482ce95a2e3c.png)

### Figma Link
https://www.figma.com/file/aIGds1IG7Kz03UBOakEKjf/Code-Sauce-Website-Design?node-id=0%3A1

**Comment by Divyanshj** [comment]
@SHITIZ-AGGARWAL Please assign this issue to me .

**Comment by SHITIZ-AGGARWAL** [comment]
Sure go ahead
