### ISSUE TITLE
feat: create projects page

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [Code-Sauce-Official/Website#3]
### Make projects page for code sauce

![image](https://user-images.githubusercontent.com/53532851/123140329-ca48de00-d474-11eb-9ee9-6140c78f9156.png)

### Figma Link
https://www.figma.com/file/aIGds1IG7Kz03UBOakEKjf/Code-Sauce-Website-Design?node-id=0%3A1

**Comment by ayushsagar10** [comment]
Please assign this issue to me

**Comment by SHITIZ-AGGARWAL** [comment]
Sure go ahead
